name: conventional release labels

on:
  pull_request_target:
    types: 
      - opened
      - edited      

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          ignored_types: '["chore", "ci"]'
          type_labels: '{"feat": "enhancement", "fix": "bug", "breaking": "breaking", "doc": "documentation"}'
